apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.secondIngress.name }}
spec:
  ingressClassName: {{ .Values.secondIngress.ingressClassName }}
  rules:
  - http:
      paths:
      - path: {{ .Values.secondIngress.rules.http.paths.path }}
        pathType: {{ .Values.secondIngress.rules.http.paths.pathType }}
        backend:
          service:
            name: {{ .Values.secondIngress.rules.http.paths.backend.service.name }}
            port:
              number: {{ .Values.secondIngress.rules.http.paths.backend.service.port.number }}
