apiVersion: v1
kind: Pod
metadata:
  name: {{ .Values.pod.name }}
  namespace: {{ .Values.pod.namespace }}
  labels:
    access: {{ .Values.pod.labels.access }}
    app: {{ .Values.pod.labels.app }}
spec:
  containers:
  - name: {{ .Values.pod.containers.name }}
    image: {{ .Values.pod.containers.image }}
    command: ["sleep", "3600"]
