apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.secondDeployment.name }}
spec:
  replicas: {{ .Values.secondDeployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.secondDeployment.selector.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.secondDeployment.template.labels.app }}
    spec:
      containers:
      - name: {{ .Values.secondDeployment.template.containers.name }}
        image: {{ .Values.secondDeployment.template.containers.image }}
        imagePullPolicy: {{ .Values.secondDeployment.template.containers.imagePullPolicy }}
        resources:
          requests:
            memory: {{ .Values.secondDeployment.template.containers.resources.requests.memory }}
            cpu: {{ .Values.secondDeployment.template.containers.resources.requests.cpu }}
          limits:
            memory: {{ .Values.secondDeployment.template.containers.resources.limits.memory }}
            cpu: {{ .Values.secondDeployment.template.containers.resources.limits.cpu }}
        ports:
        - containerPort: {{ .Values.secondDeployment.template.containers.ports.containerPort }}
      imagePullSecrets:
      - name: {{ .Values.secondDeployment.template.imagePullSecrets.name }}
