name: Full CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm install
        working-directory: ./src/app1
      - run: npm test
        working-directory: ./src/app1

  build-and-push-docker-images:
    needs: unit-tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t elyes28/nuageup:app1 ./src/app1
      - run: docker push elyes28/nuageup:app1
      - run: docker build -t elyes28/nuageup:app2 ./src/app2
      - run: docker push elyes28/nuageup:app2



  lint-and-package-helm-charts:
    needs: build-and-push-docker-images
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: azure/setup-helm@v1
      - run: helm lint ./helm
      - run: helm package ./helm


  deploy-to-eks:
    needs: lint-and-package-helm-charts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Update kubeconfig
        run: aws eks --region ${{ secrets.AWS_REGION }} update-kubeconfig --name Nuageup-kube 
      - name: Create DockerHub secret for Kubernetes
        run: |
          kubectl create secret docker-registry dockerhub-secret \
            --docker-username=${{ secrets.DOCKER_USERNAME }} \
            --docker-password=${{ secrets.DOCKER_PASSWORD }} \
            --docker-email=bachq2@gmail.com  
      - name: Install or Upgrade ingress-nginx
        run: |
          helm upgrade --install ingress-nginx ingress-nginx \
            --repo https://kubernetes.github.io/ingress-nginx \
            --namespace ingress-nginx \
            --create-namespace        
      - name: Deploy the ressources to EKS using Helm
        run: |
          helm upgrade --install helm ./helm --namespace default --create-namespace

